# Schema for the configuration files of the Personal Blog theme.
personal_blog.settings:
  type: theme_settings
  label: 'Personal Blog settings'
  mapping:
    font_size:
      type: integer
      label: Font size
