label: 'Strona edycji widoku.'
tips:
  views-main:
    label: 'Zarządzaj ustawieniami widoku.'
    body: 'Pokaż lub edytuj konfigurację.'
  views-ui-displays:
    label: 'Formaty wyświetlania dla tego widoku.'
    body: 'Format wyświetlania znaczy tyle co sposób w jaki wyświetlone będą wyniki, np. jako strona lub blok. Widok może posiadać więcej niż jeden format wyświetlania, które zostaną wyświetlone w tym miejscu. Aktywny format wyświetlania został wyróżniony.'
  views-ui-view-admin:
    label: 'Administracja widoku'
    body: 'Wykonaj czynności administracyjne, wliczając w sklonowanie tudzież dodanie opisu. Kliknij w przycisk rozwijania listy by zobaczyć wszystkie dostępne opcje.'
  views-ui-format:
    label: 'Format wyjściowy'
    body: 'Wybierz w jaki sposób mają zostać zaprezentowane wyniki. Np. wybierz <em>Zawartość</em> by wyświetlić każdą pozycję w całości, korzystając z własnych ustawień konfiguracji wyświetlania. Możesz również wybrać <em>Pola</em> które pozwolą Ci zaprezentować jedynie wybrane przez Ciebie pola. Poprzez zainstalowanie modułów można <em>rozszerzyć</em> podstawową funkcjonalność Drupala o dodatkowe formaty.'
  views-ui-fields:
    label: Pola
    body: 'Jeśli widok korzysta z pól, zostaną one zaprezentowane w tym miejscu. Możesz kliknąć w pole aby je skonfigurować.'
  views-ui-filter:
    label: 'Przefiltruj swój widok'
    body: 'Dodaj filtry aby ograniczyć wyniki, np. by pokazać jedynie zawartość która jest <em>opublikowana</em> należy dodać filtr <em>Opublikowane</em> i wybrać <em>Tak</em>.'
  views-ui-filter-operations:
    label: 'Przefiltruj akcje'
    body: 'Dodaj, uporządkuj lub usuń filtry.'
  views-ui-sorts:
    label: 'Kryteria sortowania'
    body: 'Zarządzaj kolejnością w jakiej wyświetlane są wyniki. Kliknij w aktywną regułę by ją skonfigurować.'
  views-ui-sorts-operations:
    label: 'Akcje sortowania'
    body: 'Dodaj, zmień kolejność lub usuń regułę sortowania.'
  views-ui-preview:
    label: Podgląd
    body: 'Pokaż podgląd widoku.'
