cdn_provider: ''
_core:
  default_config_hash: _5qrDuRmWmRVjW00si3U1s1NrgrocA4N653EYGRfgEE
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://blog.dev:8080/themes/custom/jp_blog/favicon.ico'
  use_default: 1
schemas:
  bootstrap: 8000
  jp_blog: 8000
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 1
fluid_container: 1
table_responsive: '-1'
table: ''
