version: '3'
services:
  web:
    image: drupaldocker/nginx:1.13-2.x
    env_file:
      - .env
    depends_on:
      - php
    networks:
      - frontend
      - proxy
    volumes:
      - private-files:/var/www/html/drupal-files
      - public-files:/var/www/html/web/sites/default/files
      - test-files:/var/www/html/web/sites/simpletest
      - tmp:/tmp
      - ./:/var/www/html

  php:
    build:
      context: .
      dockerfile: .drupal-docker/fpm.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - frontend
      - backend
    volumes:
      - private-files:/var/www/html/drupal-files
      - public-files:/var/www/html/web/sites/default/files
      - test-files:/var/www/html/web/sites/simpletest
      - tmp:/tmp
      - ./:/var/www/html

  db:
    image: drupaldocker/mariadb:10.3
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - db:/var/lib/mysql

  cron:
    build:
      context: .
      dockerfile: .drupal-docker/cron.Dockerfile
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
        NAME: ${USER}
    depends_on:
      - db
      - php
    networks:
      - frontend
      - backend
    volumes:
      - private-files:/var/www/html/drupal-files
      - public-files:/var/www/html/web/sites/default/files
      - tmp:/tmp
      - ./:/var/www/html

networks:
  frontend:
  backend:
  proxy:
    external:
      name: proxy

volumes:
  public-files:
  private-files:
  test-files:
  tmp:
  db:
