version: '3'
services:
  cli:
    build:
      context: .
      dockerfile: .drupal-docker/cli.Dockerfile
      args:
        UID: ${HOST_UID}
        GID: ${HOST_GID}
        NAME: ${USER}
    command: /bin/sh
    depends_on:
    - db
    - php
    networks:
    - frontend
    - backend
    environment:
    - SSH_AUTH_SOCK=/tmp/authsock
    volumes:
    - $SSH_AUTH_SOCK:/tmp/authsock
    - private-files:/var/www/html/drupal-files
    - public-files:/var/www/html/web/sites/default/files
    - test-files:/var/www/html/web/sites/simpletest
    - tmp:/tmp
    - ./:/var/www/html
    - ~/.gitconfig:/etc/gitconfig
