name: Deploy to production
on:
  push:
    branches:
      - 2.x

jobs:
  build:
    name: Build the codebase
    runs-on: ['self-hosted', 'deploy']
    timeout-minutes: 5
    steps:
      - name: Deploy
        run: cd $WORKSPACE && git pull && composer install && drush cr && drush -y updb && drush -y cim
        env:
          WORKSPACE: ${{ secrets.WORKSPACE }}
